
services:
  # Serviço da Aplicação Rails
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app # Mapeia o diretório local da aplicação para /app no container
    ports:
      - "3001:3000" # Mapeia a porta 3000 do host para a porta 3000 do container
    depends_on:
      - db # Garante que o banco de dados seja iniciado antes da aplicação
    env_file:
      - .env
    environment:
      RAILS_ENV: development 

 
  db:
    image: postgres:14 # Use uma versão específica e leve do PostgreSQL
    volumes:
      - postgres:/var/lib/postgresql/data # Volume persistente para os dados do banco
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo 

  # Serviço do PGAdmin (Interface gráfica para PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4 # Imagem oficial do PGAdmin 4
    env_file:
      - .env
    ports:
      - "4001:80" # Mapeia a porta 5050 do host para a porta 80 do container PGAdmin
    volumes:
    - pgadmin:/var/lib/pgadmin
    depends_on:
      - db # Garante que o banco de dados esteja pronto antes do PGAdmin

volumes:
  postgres:
  pgadmin: # Define o volume persistente para o PostgreSQL